In [4]:
import pandas as pd

df1 = pd.read_csv("wallets1.csv")
df1 = df1.drop_duplicates()

df2 = pd.read_csv("wallets2.csv")
df2 = df2.drop_duplicates()

df3 = pd.merge(df1, df2, on='Wallet', how='inner')
df3
#df3.to_csv("wallet1AND2.csv")

                                        Wallet
0   0xaa75b925561e6944711b014617767b699c3c4966
1   0x713e5145c3152201a54d1a1aabc9e5b482063515
2   0xd103855b83ff26e0e6a67a0203e45455f37ca713
3   0xc922706e0895f4c6caf7d27fbc433d5b92843861
4   0xdc1d18df7182b285a69502ab7c08d9a2aa2bdfae
5   0xe95b3f559b9da49fbc3f95976a76d91168d854f8
6   0x6fe9833a1cb196da70d0803bd2bf015a8025eda2
7   0x531e675dd14a2dea4e624d108cd2f180f1086844
8   0x67e02a79405c0b3500a53adfda9147ca3efb4967
9   0xd9aee31af9c9f9c59e36e40c10c2af803d6c8742
10  0x8160abf4764ebae5e07238521c73633ab143e3cc
11  0xdc66ddecd799b88eeee8dd6737f0ed1b1a45669e
12  0x05358c91ee5c9efc6e3423a3c485386d887cc34a
13  0x77e09dc0007be14aa6ce1d6292a98a2e86fb3947
14  0x9dc3dbb62a5a05e60c278e0e0cdeaf76a20a8153
15  0x57be281a20405d1edb797cfe0b7bed1f6592e9b5
16  0x3674c393a275e1b60097f43afaf424238b7856dc
17  0x3e931ec29f86698f943a486128c8d6f99bff619c
18  0x7ba8aade2f2927df24622a908bae2fa5e8f02c17
19  0x20316221c119a8504e6bdaedeee3bcbe0771419f
20  0x85589fab6abe56336fb4b9a4e33e91e3f6ce0d71
21  0x96da69cfa097d9951a11654e73a506d54532365f
22  0xa2eaba9af6795e8eaf895ad1b665660c59de98cf
23  0x5dc55530d9972a243ceee41cfa79718a28051995
24  0x27e3480d03964ffe4143ff123dbd6d62c72d5e5f
25  0x17b11ed010e715bf4336a88489fe4f0ef6a09dc7
26  0x4206db5b280263877f5374304d226b0b69605868
27  0x7a250d5630b4cf539739df2c5dacb4c659f2488d
28  0x0021c029c335d5f1a8397247ef8b9a6907038cfb
29  0x28db1cab00c242e341f82e3f250aa02204355ee3
30  0xcea84bf56337ab2e8eca46466285a15d1fa94eb9
31  0xc383fe637b27daefdba996f832dc40402a49f57b
32  0xf90e8f8a87116acf398097dc6ed8fb4ef105c05b
33  0x3eadcf3a491e710a5a65ddfa739211b6930a27e9
34  0x20de608929b026ef24a424ced75b828a3b56fc4d
35  0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45
36  0xcc253ddea3778232e921004e09cdea3360a73c9e
37  0xa3366e2ad9782a371a29a7c9f3a0055511f24485
38  0x5167ad8f32358b9d08b01a77b8d2c65e778cf4c9
39  0x385ba5fc690348e23387614327ea13fa9edd95b7
40  0x1fce7b2cdd7296395674da2896ade417163590d4
41  0x5fbe4f165d0e81cbe2c0e8475b935c9ad9f00e61
42  0xc879fa366f29592798daf0eb8540bcfba3fc2abd
43  0x0879de98aafd557d9fda725c311b14d2e969fe10

In [3]:
import pandas as pd

df4 = pd.read_csv("wallets3.csv")
df4 = df4.drop_duplicates()

df5 = pd.read_csv("wallets1AND2.csv")
df5 = df5.drop_duplicates()

df6 = pd.merge(df4, df5, on='Wallet', how='inner')
df6

                                       Wallet  Unnamed: 0
0  0xdc66ddecd799b88eeee8dd6737f0ed1b1a45669e          11
1  0x67e02a79405c0b3500a53adfda9147ca3efb4967           8
2  0x20de608929b026ef24a424ced75b828a3b56fc4d          34
3  0x3eadcf3a491e710a5a65ddfa739211b6930a27e9          33
4  0x7a250d5630b4cf539739df2c5dacb4c659f2488d          27
5  0xcea84bf56337ab2e8eca46466285a15d1fa94eb9          30
6  0x9dc3dbb62a5a05e60c278e0e0cdeaf76a20a8153          14
7  0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45          35

In [9]:
#DONKEY
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.5f' % x)

donkey = pd.read_csv("donkey.csv")
ODAholders = pd.read_csv("donkeyHOLDERS.csb.csv")
ODAholders = ODAholders[ODAholders['Balance'] > 52000000]

holders3 = pd.merge(donkey, ODAholders, on='HolderAddress', how='inner')
holders3

holders3 = holders3.groupby(['HolderAddress']).size().reset_index(name='counts')
holders3.sort_values('counts', ascending=False)

                                 HolderAddress  counts
8   0x3b6389c9b3b667871d6780cf96bbf11c5214fa66       7
23  0xd5eb67335fabb0c5dc9f4ca0d7ed65ce3188c805       6
21  0xc91f9320ea07db41998af9784c0df1b313adbc6c       5
4   0x27b54282bc592bf533e48f700829abb5d0a45b78       4
22  0xd3247f1616a755fbbaafe6fb62af266edcab6e5a       4
1   0x0a6149903de93b91870288d48dc1d40b02c16945       4
11  0x58911f40533bd4b2efd020adca1176c8c92e5c1f       2
16  0x917c94cc8c02314a371a0db2470dd0c50873cbd5       2
15  0x7e86c00d438d3aede93e9e50049bafb6888a5c6b       2
12  0x676e431dc34cc78964bb85a17275c86116ebdbfe       2
20  0xc851a497e15402aea6b852026213950c58d312ff       2
10  0x577c41cc6b72c5c20322e1c3d65bcace9898bcca       2
7   0x2e2cba71db91853db02ba2e2cd53e5adf050eea9       2
6   0x2d74d583c75dc9ecc69e7a7a79df4b3312188c2c       2
24  0xdbc61967c9515cb0349600c2f614fa135b6a17ec       2
25  0xec641c2181b6a3b9f202645eb56adc652f4563bd       2
2   0x0eaf80504b28c0c84957c2955cc2d86a63e3840e       2
19  0xaf9eb7708054dafada9ae78528751a1934f38caa       1
0   0x08a943acbfed228036ae3328a7845fe3be545b73       1
13  0x71c38b9125e43620de3af53e1e5458a4cdcbc7c9       1
18  0xabbe3f5fb5df55a3be9962962696871c67515f0f       1
17  0x93714b021d0a57333d93998c99c1c3394d47dc19       1
14  0x7ac712278189528886b26459576f1438a99dbfff       1
9   0x52c3af1df5d1fcab0d5d095c8d1546a6b83f2c2b       1
5   0x282aaf3097a22194264beff53e8ae8003122b841       1
3   0x250640b16a0502538c659817d343c539e6d935e2       1
26  0xef7e70f08ec52f7d5c1da613eacfa428fa816a4c       1

In [1]:
#THANOS
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.5f' % x)

donkey = pd.read_csv("THANOS.csv")
aicapHolders = pd.read_csv("THANOSholders.csv")
aicapHolders = aicapHolders[aicapHolders['Balance'] >= 1000]

holders4 = pd.merge(donkey, aicapHolders, on='HolderAddress', how='inner')
holders4

holders4 = holders4.groupby(['HolderAddress']).size().reset_index(name='counts')
holders4.sort_values('counts', ascending=False)

                                HolderAddress  counts
0  0x73637d4b2b9e9bba469fc0ee1608a5c6fe4c339a       1